# site settings
title: elliott
subtitle: etc
email: elliott@elliott.io
description: I've managed dozens of people in large scale art installations, raised millions in institutional capital for my own ML startup, helped large organizations understand and improve their culture through day-long workshops and year-long projects. I started the first coworking space in Pittsburgh, and helped a dozen waring cafes become kinder to each other. But no matter what title, I've always called myself a designer. What other profession can call empathy and thoughtfulness core competencies?
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 5407 Black St
city: Pittsburgh
state: PA
zip_code: 15206
country: United States of America
phone: 01 412 979 1774

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: http://linkedin.com/in/elliottw
pinterest_url:
slack_url:
twitter_url: https://twitter.com/elliottwilliams

# build settings
markdown: kramdown

sass:
  style: compressed
